# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\work\TrackVFX\tk\tvfx-maya-playblast\resources\dialog.ui'
#
# Created: Wed May 12 16:04:22 2021
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

# from PySide import QtCore, QtGui
try:
    from sgtk.platform.qt import QtCore, QtGui
except ImportError:
    from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(489, 402)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.finalRes_label = QtGui.QLabel(self.groupBox_3)
        self.finalRes_label.setObjectName("finalRes_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.finalRes_label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_resolution = QtGui.QComboBox(self.groupBox_3)
        self.cb_resolution.setObjectName("cb_resolution")
        self.cb_resolution.addItem("")
        self.cb_resolution.addItem("")
        self.cb_resolution.addItem("")
        self.horizontalLayout.addWidget(self.cb_resolution)
        self.sb_res_w = QtGui.QSpinBox(self.groupBox_3)
        self.sb_res_w.setMaximum(20000)
        self.sb_res_w.setObjectName("sb_res_w")
        self.horizontalLayout.addWidget(self.sb_res_w)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sb_res_h = QtGui.QSpinBox(self.groupBox_3)
        self.sb_res_h.setMaximum(20000)
        self.sb_res_h.setObjectName("sb_res_h")
        self.horizontalLayout.addWidget(self.sb_res_h)
        self.tb_resolution_preset = QtGui.QToolButton(self.groupBox_3)
        self.tb_resolution_preset.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.tb_resolution_preset.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tb_resolution_preset.setAutoRaise(True)
        self.tb_resolution_preset.setObjectName("tb_resolution_preset")
        self.horizontalLayout.addWidget(self.tb_resolution_preset)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_6_focalLength = QtGui.QLabel(self.groupBox_3)
        self.label_6_focalLength.setObjectName("label_6_focalLength")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6_focalLength)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sb_focal = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.sb_focal.setPrefix("")
        self.sb_focal.setProperty("value", 35.0)
        self.sb_focal.setObjectName("sb_focal")
        self.horizontalLayout_6.addWidget(self.sb_focal)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_1_frameRange = QtGui.QLabel(self.groupBox_3)
        self.label_1_frameRange.setObjectName("label_1_frameRange")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_1_frameRange)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.le_frame_start = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_frame_start.sizePolicy().hasHeightForWidth())
        self.le_frame_start.setSizePolicy(sizePolicy)
        self.le_frame_start.setMaximumSize(QtCore.QSize(53, 16777215))
        self.le_frame_start.setText("")
        self.le_frame_start.setObjectName("le_frame_start")
        self.horizontalLayout_2.addWidget(self.le_frame_start)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.le_frame_end = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_frame_end.sizePolicy().hasHeightForWidth())
        self.le_frame_end.setSizePolicy(sizePolicy)
        self.le_frame_end.setMaximumSize(QtCore.QSize(53, 16777215))
        self.le_frame_end.setText("")
        self.le_frame_end.setObjectName("le_frame_end")
        self.horizontalLayout_2.addWidget(self.le_frame_end)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_scale = QtGui.QLabel(self.groupBox_3)
        self.label_scale.setObjectName("label_scale")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_scale)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sb_scale = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.sb_scale.setMaximum(1.0)
        self.sb_scale.setSingleStep(0.1)
        self.sb_scale.setProperty("value", 0.5)
        self.sb_scale.setObjectName("sb_scale")
        self.horizontalLayout_3.addWidget(self.sb_scale)
        spacerItem3 = QtGui.QSpacerItem(120, 12, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_format = QtGui.QLabel(self.groupBox_3)
        self.label_format.setObjectName("label_format")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_format)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cb_format = QtGui.QComboBox(self.groupBox_3)
        self.cb_format.setObjectName("cb_format")
        self.cb_format.addItem("")
        self.cb_format.addItem("")
        self.horizontalLayout_4.addWidget(self.cb_format)
        spacerItem4 = QtGui.QSpacerItem(117, 9, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_framePadding = QtGui.QLabel(self.groupBox_3)
        self.label_framePadding.setObjectName("label_framePadding")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_framePadding)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sb_padding = QtGui.QSpinBox(self.groupBox_3)
        self.sb_padding.setProperty("value", 4)
        self.sb_padding.setObjectName("sb_padding")
        self.horizontalLayout_5.addWidget(self.sb_padding)
        spacerItem5 = QtGui.QSpacerItem(114, 6, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_2)
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.checkBox)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5_cameraType = QtGui.QLabel(self.frame)
        self.label_5_cameraType.setObjectName("label_5_cameraType")
        self.gridLayout_4.addWidget(self.label_5_cameraType, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cb_camera_type = QtGui.QComboBox(self.frame)
        self.cb_camera_type.setObjectName("cb_camera_type")
        self.cb_camera_type.addItem("")
        self.cb_camera_type.addItem("")
        self.cb_camera_type.addItem("")
        self.cb_camera_type.addItem("")
        self.cb_camera_type.addItem("")
        self.horizontalLayout_8.addWidget(self.cb_camera_type)
        self.le_camera_custom = QtGui.QLineEdit(self.frame)
        self.le_camera_custom.setObjectName("le_camera_custom")
        self.horizontalLayout_8.addWidget(self.le_camera_custom)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.label_4_passType = QtGui.QLabel(self.frame)
        self.label_4_passType.setObjectName("label_4_passType")
        self.gridLayout_4.addWidget(self.label_4_passType, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cb_pass_type = QtGui.QComboBox(self.frame)
        self.cb_pass_type.setObjectName("cb_pass_type")
        self.cb_pass_type.addItem("")
        self.cb_pass_type.addItem("")
        self.cb_pass_type.addItem("")
        self.cb_pass_type.addItem("")
        self.cb_pass_type.addItem("")
        self.horizontalLayout_9.addWidget(self.cb_pass_type)
        self.le_pass_type_custom = QtGui.QLineEdit(self.frame)
        self.le_pass_type_custom.setObjectName("le_pass_type_custom")
        self.horizontalLayout_9.addWidget(self.le_pass_type_custom)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.label_comment = QtGui.QLabel(self.frame)
        self.label_comment.setObjectName("label_comment")
        self.gridLayout_4.addWidget(self.label_comment, 2, 0, 1, 1)
        self.le_comments = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_comments.sizePolicy().hasHeightForWidth())
        self.le_comments.setSizePolicy(sizePolicy)
        self.le_comments.setObjectName("le_comments")
        self.gridLayout_4.addWidget(self.le_comments, 2, 1, 1, 1)
        self.createPlayblast = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.createPlayblast.setFont(font)
        self.createPlayblast.setObjectName("createPlayblast")
        self.gridLayout_4.addWidget(self.createPlayblast, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hl_control_layout_3 = QtGui.QHBoxLayout()
        self.hl_control_layout_3.setObjectName("hl_control_layout_3")
        self.verticalLayout_2.addLayout(self.hl_control_layout_3)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "The Current Sgtk Environment", None, QtGui.QApplication.UnicodeUTF8))
        self.finalRes_label.setText(QtGui.QApplication.translate("Dialog", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_resolution.setItemText(0, QtGui.QApplication.translate("Dialog", "From Viewport", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_resolution.setItemText(1, QtGui.QApplication.translate("Dialog", "From Render Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_resolution.setItemText(2, QtGui.QApplication.translate("Dialog", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.tb_resolution_preset.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6_focalLength.setText(QtGui.QApplication.translate("Dialog", "Focal length", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_focal.setSuffix(QtGui.QApplication.translate("Dialog", " mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1_frameRange.setText(QtGui.QApplication.translate("Dialog", "Frame Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_scale.setText(QtGui.QApplication.translate("Dialog", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_format.setText(QtGui.QApplication.translate("Dialog", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_format.setItemText(0, QtGui.QApplication.translate("Dialog", "avi", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_format.setItemText(1, QtGui.QApplication.translate("Dialog", "image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_framePadding.setText(QtGui.QApplication.translate("Dialog", "FramePadding", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Off Screen", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "Yes/No?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5_cameraType.setText(QtGui.QApplication.translate("Dialog", "Camera Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_camera_type.setItemText(0, QtGui.QApplication.translate("Dialog", "Freemove", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_camera_type.setItemText(1, QtGui.QApplication.translate("Dialog", "Lockoff", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_camera_type.setItemText(2, QtGui.QApplication.translate("Dialog", "Nodal", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_camera_type.setItemText(3, QtGui.QApplication.translate("Dialog", "Static", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_camera_type.setItemText(4, QtGui.QApplication.translate("Dialog", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4_passType.setText(QtGui.QApplication.translate("Dialog", "Pass Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pass_type.setItemText(0, QtGui.QApplication.translate("Dialog", "Godcam", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pass_type.setItemText(1, QtGui.QApplication.translate("Dialog", "Greyshade", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pass_type.setItemText(2, QtGui.QApplication.translate("Dialog", "Stabilization", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pass_type.setItemText(3, QtGui.QApplication.translate("Dialog", "Wireframe", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pass_type.setItemText(4, QtGui.QApplication.translate("Dialog", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_comment.setText(QtGui.QApplication.translate("Dialog", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.le_comments.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Please describe your work..", None, QtGui.QApplication.UnicodeUTF8))
        self.createPlayblast.setText(QtGui.QApplication.translate("Dialog", "Playblast!", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
