# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from sgtk.platform.qt import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(402, 353)
        self.formLayout_3 = QtGui.QFormLayout(Dialog)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5_cameraType = QtGui.QLabel(self.frame)
        self.label_5_cameraType.setObjectName(_fromUtf8("label_5_cameraType"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5_cameraType)
        self.label_4_passType = QtGui.QLabel(self.frame)
        self.label_4_passType.setObjectName(_fromUtf8("label_4_passType"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4_passType)
        self.label_comment = QtGui.QLabel(self.frame)
        self.label_comment.setObjectName(_fromUtf8("label_comment"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_comment)
        self.le_comments = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_comments.sizePolicy().hasHeightForWidth())
        self.le_comments.setSizePolicy(sizePolicy)
        self.le_comments.setObjectName(_fromUtf8("le_comments"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_comments)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.cb_camera_type = QtGui.QComboBox(self.frame)
        self.cb_camera_type.setObjectName(_fromUtf8("cb_camera_type"))
        self.cb_camera_type.addItem(_fromUtf8(""))
        self.cb_camera_type.addItem(_fromUtf8(""))
        self.cb_camera_type.addItem(_fromUtf8(""))
        self.cb_camera_type.addItem(_fromUtf8(""))
        self.cb_camera_type.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.cb_camera_type)
        self.le_camera_custom = QtGui.QLineEdit(self.frame)
        self.le_camera_custom.setObjectName(_fromUtf8("le_camera_custom"))
        self.horizontalLayout_8.addWidget(self.le_camera_custom)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cb_pass_type = QtGui.QComboBox(self.frame)
        self.cb_pass_type.setObjectName(_fromUtf8("cb_pass_type"))
        self.cb_pass_type.addItem(_fromUtf8(""))
        self.cb_pass_type.addItem(_fromUtf8(""))
        self.cb_pass_type.addItem(_fromUtf8(""))
        self.cb_pass_type.addItem(_fromUtf8(""))
        self.cb_pass_type.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.cb_pass_type)
        self.le_pass_type_custom = QtGui.QLineEdit(self.frame)
        self.le_pass_type_custom.setObjectName(_fromUtf8("le_pass_type_custom"))
        self.horizontalLayout_9.addWidget(self.le_pass_type_custom)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.createPlayblast = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.createPlayblast.setFont(font)
        self.createPlayblast.setObjectName(_fromUtf8("createPlayblast"))
        self.horizontalLayout_7.addWidget(self.createPlayblast)
        self.pb_cancel = QtGui.QPushButton(self.frame)
        self.pb_cancel.setObjectName(_fromUtf8("pb_cancel"))
        self.horizontalLayout_7.addWidget(self.pb_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.SpanningRole, self.frame)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.finalRes_label = QtGui.QLabel(self.groupBox_3)
        self.finalRes_label.setObjectName(_fromUtf8("finalRes_label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.finalRes_label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sb_res_w = QtGui.QSpinBox(self.groupBox_3)
        self.sb_res_w.setMaximum(20000)
        self.sb_res_w.setObjectName(_fromUtf8("sb_res_w"))
        self.horizontalLayout.addWidget(self.sb_res_w)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.sb_res_h = QtGui.QSpinBox(self.groupBox_3)
        self.sb_res_h.setMaximum(20000)
        self.sb_res_h.setObjectName(_fromUtf8("sb_res_h"))
        self.horizontalLayout.addWidget(self.sb_res_h)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_1_frameRange = QtGui.QLabel(self.groupBox_3)
        self.label_1_frameRange.setObjectName(_fromUtf8("label_1_frameRange"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_1_frameRange)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.le_frame_start = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_frame_start.sizePolicy().hasHeightForWidth())
        self.le_frame_start.setSizePolicy(sizePolicy)
        self.le_frame_start.setMaximumSize(QtCore.QSize(53, 16777215))
        self.le_frame_start.setText(_fromUtf8(""))
        self.le_frame_start.setObjectName(_fromUtf8("le_frame_start"))
        self.horizontalLayout_2.addWidget(self.le_frame_start)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.le_frame_end = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_frame_end.sizePolicy().hasHeightForWidth())
        self.le_frame_end.setSizePolicy(sizePolicy)
        self.le_frame_end.setMaximumSize(QtCore.QSize(53, 16777215))
        self.le_frame_end.setText(_fromUtf8(""))
        self.le_frame_end.setObjectName(_fromUtf8("le_frame_end"))
        self.horizontalLayout_2.addWidget(self.le_frame_end)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_scale = QtGui.QLabel(self.groupBox_3)
        self.label_scale.setObjectName(_fromUtf8("label_scale"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_scale)
        self.label_format = QtGui.QLabel(self.groupBox_3)
        self.label_format.setObjectName(_fromUtf8("label_format"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_format)
        self.label_framePadding = QtGui.QLabel(self.groupBox_3)
        self.label_framePadding.setObjectName(_fromUtf8("label_framePadding"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_framePadding)
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.checkBox)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sb_scale = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.sb_scale.setMaximum(1.0)
        self.sb_scale.setSingleStep(0.1)
        self.sb_scale.setProperty("value", 0.5)
        self.sb_scale.setObjectName(_fromUtf8("sb_scale"))
        self.horizontalLayout_3.addWidget(self.sb_scale)
        spacerItem2 = QtGui.QSpacerItem(120, 12, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cb_format = QtGui.QComboBox(self.groupBox_3)
        self.cb_format.setObjectName(_fromUtf8("cb_format"))
        self.cb_format.addItem(_fromUtf8(""))
        self.cb_format.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cb_format)
        spacerItem3 = QtGui.QSpacerItem(117, 9, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.sb_padding = QtGui.QSpinBox(self.groupBox_3)
        self.sb_padding.setProperty("value", 4)
        self.sb_padding.setObjectName(_fromUtf8("sb_padding"))
        self.horizontalLayout_5.addWidget(self.sb_padding)
        spacerItem4 = QtGui.QSpacerItem(114, 6, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_6_focalLength = QtGui.QLabel(self.groupBox_3)
        self.label_6_focalLength.setObjectName(_fromUtf8("label_6_focalLength"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6_focalLength)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.sb_focal = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.sb_focal.setPrefix(_fromUtf8(""))
        self.sb_focal.setProperty("value", 35.0)
        self.sb_focal.setObjectName(_fromUtf8("sb_focal"))
        self.horizontalLayout_6.addWidget(self.sb_focal)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.SpanningRole, self.groupBox_3)
        self.label_comment.raise_()
        self.groupBox_3.raise_()
        self.createPlayblast.raise_()
        self.label_6_focalLength.raise_()
        self.sb_scale.raise_()
        self.cb_format.raise_()
        self.sb_padding.raise_()
        self.sb_focal.raise_()
        self.cb_pass_type.raise_()
        self.label_5_cameraType.raise_()
        self.label_4_passType.raise_()
        self.cb_camera_type.raise_()
        self.pb_cancel.raise_()
        self.frame.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "The Current Sgtk Environment", None))
        self.label_5_cameraType.setText(_translate("Dialog", "Camera Type", None))
        self.label_4_passType.setText(_translate("Dialog", "Pass Type", None))
        self.label_comment.setText(_translate("Dialog", "Comment", None))
        self.le_comments.setPlaceholderText(_translate("Dialog", "Please describe your work..", None))
        self.cb_camera_type.setItemText(0, _translate("Dialog", "Freemove", None))
        self.cb_camera_type.setItemText(1, _translate("Dialog", "Lockoff", None))
        self.cb_camera_type.setItemText(2, _translate("Dialog", "Nodal", None))
        self.cb_camera_type.setItemText(3, _translate("Dialog", "Static", None))
        self.cb_camera_type.setItemText(4, _translate("Dialog", "Custom", None))
        self.cb_pass_type.setItemText(0, _translate("Dialog", "Godcam", None))
        self.cb_pass_type.setItemText(1, _translate("Dialog", "Greyshade", None))
        self.cb_pass_type.setItemText(2, _translate("Dialog", "Stabilization", None))
        self.cb_pass_type.setItemText(3, _translate("Dialog", "Wireframe", None))
        self.cb_pass_type.setItemText(4, _translate("Dialog", "Custom", None))
        self.createPlayblast.setText(_translate("Dialog", "Playblast!", None))
        self.pb_cancel.setText(_translate("Dialog", "Cancel", None))
        self.finalRes_label.setText(_translate("Dialog", "Resolution", None))
        self.label.setText(_translate("Dialog", "x", None))
        self.label_1_frameRange.setText(_translate("Dialog", "Frame Range", None))
        self.label_3.setText(_translate("Dialog", "-", None))
        self.label_scale.setText(_translate("Dialog", "Scale", None))
        self.label_format.setText(_translate("Dialog", "Format", None))
        self.label_framePadding.setText(_translate("Dialog", "FramePadding", None))
        self.checkBox.setText(_translate("Dialog", "Yes/No?", None))
        self.label_2.setText(_translate("Dialog", "Off Screen", None))
        self.cb_format.setItemText(0, _translate("Dialog", "avi", None))
        self.cb_format.setItemText(1, _translate("Dialog", "image", None))
        self.label_6_focalLength.setText(_translate("Dialog", "Focal length", None))
        self.sb_focal.setSuffix(_translate("Dialog", " mm", None))

import resources_rc
